services:
  web-tier:
    build: ./web-tier
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - app-tier
    networks:
      - app-network
    volumes:
      - ./web-tier/build:/usr/share/nginx/html       # React build for development
      - ./web-tier/nginx.conf:/etc/nginx/nginx.conf:ro  # NGINX config

  app-tier:
    build: ./app-tier
    depends_on:
      - db-tier
    ports:
      - "4000:4000"
    networks:
      - app-network
    env_file: .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  db-tier:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_USER: Jaystones
      MYSQL_PASSWORD: Jogolo4sokka
      MYSQL_ROOT_PASSWORD: Jogolo4sokka
      MYSQL_DATABASE: webappdb
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes: 
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
